### ISSUE TITLE
Parser::ClassifyString too aggressive on minus sign checking

### ISSUE THREAD

**Issue by yeahhowaboutnooo** [ThirdEyeSqueegee/ContainerItemDistributor#1]
i believe this:
https://github.com/ThirdEyeSqueegee/ContainerItemDistributor/blob/adc27213eff33f446e3912eb5395f5babb713c4e/src/Parser.cpp#L5C16-L5C16

is broken,

e.g. i tried adding the Soap from the dirt & blood mod to containers as such:

MerchantDawnstarMortarPestleChest = 0x82e~Dirt and Blood - Dynamic Visuals.esp|10

and well, there's a minus sign in that line -> log file entry:
[20:17:40.356 UTC+02:00] [D] [40340] [Parser.cpp:62] Key MerchantDawnstarMortarPestleChest has 1 values
[20:17:40.356 UTC+02:00] [D] [40340] [Parser.cpp:86] * REMOVE 0x82e~Dirt and Blood - Dynamic Visuals.esp|10/Dirt-and-Blood_buy-and-sell-Soap_CID.ini

-> CID tries removing instead of adding the item from the container

using the EditorID "Dirty_Soap" instead of FormID~PluginName results in the same erroneous REMOVE.

Edit: as the _CID.ini filename seems to be part of the distribution string (in my example above: "Dirt-and-Blood_buy-and-sell-Soap_CID.ini" ) -> these minus signs also trigger the parser to flag the entry as a REMOVE entry.

**Comment by ThirdEyeSqueegee** [comment]
Whoops sorry about the late response, just noticed this--I almost never check issues here, plz post on Nexus! Will fix this in the next update
